export const BASE_URL = 'http://localhost:8081';
export const BASE_API_URL = 'http://localhost:8081/api';

export const BACKGROUND_TYPE = '/background-type';
export const ACCOMPLISHMENT_TYPE = '/accomplishment-type';
export const INDUSTRY_TYPE = '/industry-type';
export const FORMER_NAME_VISIBILITY_TYPE = '/former-name-visibility-type';
export const POST_VISIBILITY_TYPE = '/show-post-type';
export const SKILL_LEVEL_TYPE = '/skill-level';
export const RELATION_KNOWLEDGE_TYPE = '/relation-knowledge';
export const CONNECT_TYPE = '/connect-type';
export const LANGUAGE_LEVEL_TYPE = '/language-level';
export const BACKGROUND = '/background';
export const ACCOMPLISHMENT = '/accomplishment';
export const SKILL = '/skill';
export const ADD_ALL_SKILLS = '/skill/add-all';
export const GET_SKILLS = '/skills-json';
export const ENDORSEMENT = '/endorsement';
export const LANGUAGE = '/language';
export const SIGN_UP = '/sign-up';
export const LOGIN = '/login';
export const PROFILE = '/profile';
export const FULL_PROFILE = '/profile-json';
export const PROFILE_BY_USERNAME = '/get-profile/username';
export const SEARCH_PROFILE = '/search';
export const NUM_OF_CONN = '/number-connection';
export const REQUEST_CONNECTION = '/send-pending-connection';
export const REQUEST_CONNECTIONS_SENT = '/get-sender-connection'; // requests I have sent
export const REQUEST_CONNECTIONS_RECEIVED = '/get-receiver-connection'; // requests I have received
export const RESPOND_REQUEST = '/accept-reject-connection'; // requests I have received
export const PENDING_CONNECTION_REQUESTS = '/get-pending'; // requests I have received
export const POST = '/post';
export const LIKE_POST = '/post/like';
export const REMOVE_POST_LIKE = '/post/like';
export const CREATE_COMMENT = '/post/comment';

